language: ruby
before_install:
 - sudo apt-get install libpcap-dev -qq
before_script:
 - gem update bundler
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script:
  - rvmsudo bundle exec rake
