language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
matrix:
  allow_failures:
    - rvm: ruby-head  
script:
  - rvmsudo bundle exec rake
before_install:
 - sudo apt-get install libpcap-dev -qq
 - gem update bundler  
