---
version: "{build}"
branches:
  only:
    - master
clone_depth: 10
install:
  - ps: ((New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt', "$env:TMP\ca-bundle.crt"))
  - SET SSL_CERT_FILE=%TMP%\ca-bundle.crt
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version
  - bundle install
  - cinst 7zip.commandline
  - cinst winpcap
  - appveyor DownloadFile http://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
  - dir
  - 7za x .\WpdPack_4_1_2.zip -oc:\WpdPack
build_script:
  - rake compile
test_script:
  - rake test
artifacts:
  - path: pkg\*.gem  

environment:
  matrix:
    - ruby_version: "193"
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
