---
version: "{build}"
branches:
  only:
    - master
clone_depth: 10
install:
  - ps: ((New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt', "$env:TMP\ca-bundle.crt"))
  - SET SSL_CERT_FILE=%TMP%\ca-bundle.crt
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet
  - bundler --version
  - bundle install
  - cinst 7zip.commandline
  - cinst winpcap
  - appveyor DownloadFile http://www.winpcap.org/install/bin/WpdPack_%wpdpack%.zip
  - dir
  - 7za x .\WpdPack_%wpdpack%.zip -oc:\
build_script:
  - rake gem
test_script:
  - gem install pkg\pcaprub-*.gem
artifacts:
  - path: pkg\*.gem

# https://www.appveyor.com/docs/installed-software#ruby
environment:
  wpdpack: 4_1_2
  matrix:
    - ruby_version: "24-x64"
    - ruby_version: "24"
    - ruby_version: "25-x64"
    - ruby_version: "25"
    - ruby_version: "26-x64"
    - ruby_version: "26"


cache:
  - C:\Users\appveyor\AppData\Local\Temp\chocolatey
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
